### ISSUE TITLE
road to shielded activity

### ISSUE THREAD

**Issue by panleone** [PIVX-Labs/MyPIVXWallet#335]
This is basically the last important sapling feature missing in MPW right now, shielded txs are poorly handled by the activity widget.
A list of tasks that needs to be done to finish the implementation:

- [X] Network refactor. Done in #323
- [X] Unify transparent and shield sync. Done in #340
- [X] Keep track of owned nullifiers, in order to quickly decrypt a sapling spend. Done in [pivx-shield#81](https://github.com/PIVX-Labs/pivx-shield/pull/81/files)
- [X] When handling a block, make the shield library return transactions that belong to the wallet. Done in [pivx-shield#81](https://github.com/PIVX-Labs/pivx-shield/pull/81/files)
- [X] Put everything together and implement the activity. Review needed at #416
